name: Raghav's Daily Commit

on:
  schedule:
    - cron: '*/1 * * * *'  # Every day at midnight UTC to runs every 7-8 min set cron to '*/1 * * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello, my name is raghav agarwal" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "git-raghav"
        git config --global user.email "raghavagarwal3618@gmail.com"
        git add "$FILE"
        
        arr[0]="changed backend logic"
        arr[1]="added ui features"
        arr[2]="updated README.md"
        arr[3]="update"
        arr[4]="initial commit"
        arr[5]="resolved an issue"
        arr[6]="added new features"
        arr[7]="planned new projects"
        arr[8]="updated todo"
        arr[9]="responsive"
          
        rand=$[$RANDOM % ${#arr[@]}]
          
        git commit -m "${arr[$rand]}"
        
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/git-raghav/Project-commit.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
